# Generated by Django 5.2.3 on 2025-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
